-- Eliminar las tablas si existen
DROP TABLE IF EXISTS proveedores;
DROP TABLE IF EXISTS aplicaciones;
DROP TABLE IF EXISTS productos;

-- Crear la tabla productos
CREATE TABLE productos (
    "REGISTRO" SERIAL PRIMARY KEY,
    "DESCRIPCION" VARCHAR(200) NOT NULL,
    "INGREDIENTE_ACTIVO" VARCHAR(200) NOT NULL,
    "PRODUCTO" VARCHAR(200) NOT NULL
);

-- Crear la tabla proveedores
CREATE TABLE proveedores (
    codigo INTEGER PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL,
    correo VARCHAR(100),
    telefono VARCHAR(20),
    direccion VARCHAR(200)
);

-- Crear la tabla aplicaciones
CREATE TABLE aplicaciones (
    "REGISTRO" SERIAL PRIMARY KEY,
    "FECHA" DATE,
    "CULTIVO" VARCHAR(100),
    "AREA" DECIMAL,
    "PRODUTO" VARCHAR(100),
    "DESCRICAO" TEXT,
    "INGREDIENTE_ACTIVO" VARCHAR(100),
    "DOSIS" VARCHAR(50),
    "OBJETIVO" VARCHAR(100),
    "APLICADOR" VARCHAR(100),
    "EPI" VARCHAR(200),
    "TIPO_PICO" VARCHAR(50),
    "VOL_AGUA" DECIMAL,
    "TEMPERATURA" DECIMAL,
    "HUMEDAD" DECIMAL,
    "VIENTO" DECIMAL,
    "DEPARTAMENTO" VARCHAR(100),
    "DISTRITO" VARCHAR(100),
    "LOCALIDAD" VARCHAR(100),
    "PARCELA_NRO" VARCHAR(50),
    "MATRICULA_PROFESIONAL" VARCHAR(50),
    "REGISTRO_SENAVE" VARCHAR(50),
    "ENTIDAD_COMERCIALIZADORA" VARCHAR(100),
    "REG_PRODUCTO" VARCHAR(50),
    "PRODUCTOR" VARCHAR(100),
    "RECETA_NRO" VARCHAR(50),
    "FECHA_EXP" DATE
);
