-- Agregar nuevos campos a la tabla aplicaciones
ALTER TABLE aplicaciones
ADD COLUMN "DEPARTAMENTO" VARCHAR(100),
ADD COLUMN "DISTRITO" VARCHAR(100),
ADD COLUMN "LOCALIDAD" VARCHAR(100),
ADD COLUMN "PARCELA_NRO" VARCHAR(50),
ADD COLUMN "MATRICULA_PROFESIONAL" VARCHAR(50),
ADD COLUMN "REGISTRO_SENAVE" VARCHAR(50),
ADD COLUMN "ENTIDAD_COMERCIALIZADORA" VARCHAR(200),
ADD COLUMN "REG_PRODUCTO" VARCHAR(100);
